# <font color='red'> [0] Build the model </font> 

## <font color='green'> [0.1] Importation of the package </font> 

In [1]:
from main import *

## <font color='green'> [0.2] Creation of an empty model </font> 

In [2]:
momo = MODEL()

Model created 
 
To add metabolite, use .metabolites.add_meta 
To add reaction,   use .reactions.add_reaction


## <font color='green'> [0.3] Add of reaction and metabolite </font> 

In [3]:
momo.metabolites.add(name = "H2O", external = True, concentration = 1.0)

metabolite_reaction = {"H2O" : 1.0,
                       "H2"  :-1.0,
                       "O2"  :-0.5}

momo.reactions.add(name = "combustion_H2", metabolites = metabolite_reaction, k_eq = 1.0, law = "", flux=1.0)

Don't worry, the metabolite will be add after the add of the 1st reaction
The metabolite "H2O" is already in the model !


In [4]:
metabolite_reaction2 = {"C" : -1.0,
                       "O2"  : -1.0,
                       "CO2"  : 1.0}
momo.reactions.add(name = "combustion_C", metabolites = metabolite_reaction2, k_eq = 1.0, law = "", flux=1.0)

In [5]:
momo.reactions.df

Metabolites  Equilibrium constant Law  \
combustion_H2  {'H2O': 1.0, 'H2': -1.0, 'O2': -0.5}                   1.0       
combustion_C    {'O2': -1.0, 'C': -1.0, 'CO2': 1.0}                   1.0       

               Flux (mmol/gDW/h)  
combustion_H2                  1  
combustion_C                   1

#### Add a reaction with specified metabolite and stoichiometric coefficient automaticaly adds them to the model

In [6]:
momo.metabolites.df

External  Concentration (mmol/gDW)
H2O     False                         1
H2      False                         1
O2      False                         1
C       False                         1
CO2     False                         1

#### Print the stoichiometric matrix

In [7]:
momo.Stoichio_matrix

combustion_H2  combustion_C
H2O            1.0           0.0
H2            -1.0           0.0
O2            -0.5          -1.0
C              0.0          -1.0
CO2            0.0           1.0

#### It is also possible to remove a metabolite or a reaction to the model

In [8]:
momo.metabolites.remove("O2")
momo.metabolites.df

External  Concentration (mmol/gDW)
H2O     False                         1
H2      False                         1
C       False                         1
CO2     False                         1

In [9]:
momo.elasticity.s.df

H2  H2O  C  CO2
combustion_H2   0    0  0    0
combustion_C    0    0  0    0

#### Removing a metabolite remove also every mention of it in the reactions dataframe and in the stoichiometric matrix

In [10]:
momo.reactions.df

Metabolites  Equilibrium constant Law  \
combustion_H2  {'H2O': 1.0, 'H2': -1.0}                   1.0       
combustion_C                {'C': -1.0}                   1.0       

               Flux (mmol/gDW/h)  
combustion_H2                  1  
combustion_C                   1

In [11]:
momo.Stoichio_matrix

combustion_H2  combustion_C
H2O            1.0           0.0
H2            -1.0           0.0
C              0.0          -1.0
CO2            0.0           1.0

In [12]:
momo.reactions.remove(name="combustion_C")
momo.reactions.df

Metabolites  Equilibrium constant Law  \
combustion_H2  {'H2O': 1.0, 'H2': -1.0}                   1.0       

               Flux (mmol/gDW/h)  
combustion_H2                  1

## <font color='green'> [0.4] Stoichiometric matrix from an existant one </font> 

In [13]:
reactions = {'Combustion': [1. , -1., -0.5],
            'Reaction_2': [0. ,  0.,   0. ]}

metabolites = ['H2O', 'H2', 'O2']

dataframe = pd.DataFrame(reactions, index=metabolites)

momo.Stoichio_matrix = dataframe

#### And the metabolites and reactions dataframes are automatically update

In [14]:
momo.Stoichio_matrix

Combustion  Reaction_2
H2O         1.0         0.0
H2         -1.0         0.0
O2         -0.5         0.0

In [15]:
momo.reactions.df

Metabolites  Equilibrium constant Law  \
Combustion  {'H2O': 1.0, 'H2': -1.0, 'O2': -0.5}                   1.0       
Reaction_2                                    {}                   1.0       

            Flux (mmol/gDW/h)  
Combustion                  1  
Reaction_2                  1

In [16]:
momo.metabolites.df

External  Concentration (mmol/gDW)
H2O     False                         1
H2      False                         1
O2      False                         1

## <font color='green'> [0.5] Create a linear system </font> 

In [17]:
momo.creat_linear(4)

Model created 
 
To add metabolite, use .metabolites.add_meta 
To add reaction,   use .reactions.add_reaction


### Display the variables of the system

In [18]:
momo.metabolites.df

External  Concentration (mmol/gDW)
meta_0      True                         1
meta_1     False                         1
meta_2     False                         1
meta_3      True                         1

In [19]:
momo.reactions.df

Metabolites  Equilibrium constant Law  \
reaction_0  {'meta_0': -1, 'meta_1': 1}                   1.0       
reaction_1  {'meta_1': -1, 'meta_2': 1}                   1.0       
reaction_2  {'meta_2': -1, 'meta_3': 1}                   1.0       

            Flux (mmol/gDW/h)  
reaction_0                  1  
reaction_1                  1  
reaction_2                  1

## <font color='green'> [0.6] Read a CSV file </font> 

In [20]:
momo.read_CSV()

In [21]:
momo.Stoichio_matrix

ACALD ACALDt ACKr ACONTa ACONTb ACt2r ADK1 AKGDH AKGt2r ALCD2x  ...  \
13dpg       0      0    0      0      0     0    0     0      0      0  ...   
2pg         0      0    0      0      0     0    0     0      0      0  ...   
3pg         0      0    0      0      0     0    0     0      0      0  ...   
6pgc        0      0    0      0      0     0    0     0      0      0  ...   
6pgl        0      0    0      0      0     0    0     0      0      0  ...   
...       ...    ...  ...    ...    ...   ...  ...   ...    ...    ...  ...   
s7p         0      0    0      0      0     0    0     0      0      0  ...   
succ        0      0    0      0      0     0    0     0      0      0  ...   
succ(e)     0      0    0      0      0     0    0     0      0      0  ...   
succoa      0      0    0      0      0     0    0     1      0      0  ...   
xu5p-D      0      0    0      0      0     0    0     0      0      0  ...   

        RPI SUCCt2_2 SUCCt3 SUCDi SUCOAS TALA THD2 TKT1 TKT2 TPI  
13dpg     0        0      0     0      0    0    0    0    0   0  
2pg       0        0      0     0      0    0    0    0    0   0  
3pg       0        0      0     0      0    0    0    0    0   0  
6pgc      0        0      0     0      0    0    0    0    0   0  
6pgl      0        0      0     0      0    0    0    0    0   0  
...      ..      ...    ...   ...    ...  ...  ...  ...  ...  ..  
s7p       0        0      0     0      0   -1    0    1    0   0  
succ      0        1     -1    -1     -1    0    0    0    0   0  
succ(e)   0       -1      1     0      0    0    0    0    0   0  
succoa    0        0      0     0      1    0    0    0    0   0  
xu5p-D    0        0      0     0      0    0    0   -1   -1   0  

[72 rows x 95 columns]

## <font color='green'> [0.7] Read a SBML file </font> 

In [22]:
from main import *
momo = MODEL()
momo.read_SBML()

momo.elasticity.s.half_satured()

Model created 
 
To add metabolite, use .metabolites.add_meta 
To add reaction,   use .reactions.add_reaction
Model created 
 
To add metabolite, use .metabolites.add_meta 
To add reaction,   use .reactions.add_reaction
0 error detected in your SBML file


Here, a warning occurs because one of the metabolite of the refence state file isn't in the main SBML file ( "_S__Malate" insteed of "_S_Malate" )

# <font color='red'> [1] Play with the variables </font> 

In [23]:
momo.creat_linear(4)

Model created 
 
To add metabolite, use .metabolites.add_meta 
To add reaction,   use .reactions.add_reaction


In [24]:
momo.elasticity.s.df

meta_0  meta_1  meta_2  meta_3
reaction_0       0       0       0       0
reaction_1       0       0       0       0
reaction_2       0       0       0       0

In [25]:
momo.parameters.add_externals()

In [26]:
momo.elasticity.p.df

Temperature  meta_0_para  meta_3_para
reaction_0            0          0.5         -0.0
reaction_1            0         -0.0         -0.0
reaction_2            0         -0.0         -0.5

## <font color='green'> [1.1] Display the data </font> 

### <font color='white'> [1.1.1] Display the stoichiometric matrix </font> 

In [27]:
momo.Stoichio_matrix

reaction_0  reaction_1  reaction_2
meta_0          -1           0           0
meta_1           1          -1           0
meta_2           0           1          -1
meta_3           0           0           1

### <font color='white'> [1.1.2] Display the metabolite dataframe </font> 

In [28]:
momo.metabolites.df

External  Concentration (mmol/gDW)
meta_0      True                         1
meta_1     False                         1
meta_2     False                         1
meta_3      True                         1

### <font color='white'> [1.1.3] Display the reactions dataframe </font> 

In [29]:
momo.reactions.df

Metabolites  Equilibrium constant Law  \
reaction_0  {'meta_0': -1, 'meta_1': 1}                   1.0       
reaction_1  {'meta_1': -1, 'meta_2': 1}                   1.0       
reaction_2  {'meta_2': -1, 'meta_3': 1}                   1.0       

            Flux (mmol/gDW/h)  
reaction_0                  1  
reaction_1                  1  
reaction_2                  1

### <font color='white'> [1.1.4] Display the enzymes dataframe </font> 

In [30]:
momo.enzymes.df

Empty DataFrame
Columns: [Concentration / Activity, Reactions linked]
Index: []

### <font color='white'> [1.1.5] Display the elasticities matrices </font> 

In [31]:
momo.elasticity.s.df

meta_0  meta_1  meta_2  meta_3
reaction_0       0       0       0       0
reaction_1       0       0       0       0
reaction_2       0       0       0       0

In [32]:
momo.elasticity.p

            Temperature  meta_0_para  meta_3_para
reaction_0            0          0.5         -0.0
reaction_1            0         -0.0         -0.0
reaction_2            0         -0.0         -0.5

### <font color='white'> [1.1.6] Display the enzymes dataframes </font> 

In [33]:
momo.enzymes.df

Empty DataFrame
Columns: [Concentration / Activity, Reactions linked]
Index: []

## <font color='green'> [1.2] Enzymes </font> 

#### The enzyme dataframe is initially empty

### <font color='white'> [1.2.1] Add enzymes linked to each reactions </font> 

In [34]:
momo.enzymes.add_to_all_reaction()

In [35]:
momo.enzymes.df

Concentration / Activity Reactions linked
enzyme_reaction_0                         1     [reaction_0]
enzyme_reaction_1                         1     [reaction_1]
enzyme_reaction_2                         1     [reaction_2]

### <font color='white'> [1.2.1] Add a specific enzyme </font> 

In [36]:
momo.enzymes.add(name = "name_enzyme", mean = 1.0, reaction_linked = ["PTS_RPTSsy", "PGI_R02740", "PFK_R04779"])

### <font color='white'> [1.2.1] Remove a specific enzyme </font> 

In [37]:
momo.enzymes.remove(name = "name_enzyme")

But on this state, the enzymes hasn't any influence on our study, we have to consider our enzyme as a parameters to create a elasticity between it and flux

## <font color='green'> [1.3] Parameters </font> 

### Adding a new parameters automatcally update the E_p elasticiy matix by adding a new column

There is only the temperture by default in the parameters dataframe

In [38]:
momo.parameters.df

Mean values Standard deviation
Temperature      273.15                1.0
meta_0_para         1.0                1.0
meta_3_para         1.0                1.0

### <font color='white'> [1.3.1] Add a specific parameter one by one </font> 

In [39]:
momo.parameters.add(name = "name_parameter", mean = 1.0, Standard_deviation = 0.5)

### <font color='white'> [1.3.2] Removing a specific parameter </font> 

In [40]:
momo.parameters.remove(name = "name_parameter")

Name of the removed parameter : name_parameter


### <font color='white'> [1.3.3] Add every externals metabolite as parameters </font> 

In [41]:
momo.elasticity.p.df

Temperature  meta_0_para  meta_3_para
reaction_0            0          0.5         -0.0
reaction_1            0         -0.0         -0.0
reaction_2            0         -0.0         -0.5

In [42]:
momo.parameters.add_externals()

In [43]:
momo.elasticity.p.df

Temperature  meta_0_para  meta_3_para
reaction_0            0          0.5         -0.0
reaction_1            0         -0.0         -0.0
reaction_2            0         -0.0         -0.5

In [44]:
momo.parameters.df

Mean values Standard deviation
Temperature      273.15                1.0
meta_0_para         1.0                1.0
meta_3_para         1.0                1.0

##### And the enzymes too

### <font color='white'> [1.3.4] Add every enzymes as parameters </font> 

In [45]:
momo.parameters.add_enzymes()

In [46]:
momo.parameters.df

Mean values Standard deviation
Temperature                 273.15                1.0
meta_0_para                    1.0                1.0
meta_3_para                    1.0                1.0
enzyme_reaction_0_para         1.0                1.0
enzyme_reaction_1_para         1.0                1.0
enzyme_reaction_2_para         1.0                1.0

## <font color='green'> [1.4] Elasticities </font> 

#### When the .add_externals() and .add_enzymes() are call, it automatically add default values considering the link in the dataframe

In [47]:
momo.elasticity.p.df

Temperature  meta_0_para  meta_3_para  enzyme_reaction_0_para  \
reaction_0            0          0.5         -0.0                     1.0   
reaction_1            0         -0.0         -0.0                     0.0   
reaction_2            0         -0.0         -0.5                     0.0   

            enzyme_reaction_1_para  enzyme_reaction_2_para  
reaction_0                     0.0                     0.0  
reaction_1                     1.0                     0.0  
reaction_2                     0.0                     1.0

In [48]:
momo.elasticity.s.df

meta_0  meta_1  meta_2  meta_3
reaction_0       0       0       0       0
reaction_1       0       0       0       0
reaction_2       0       0       0       0

#### We can add default value to the E_s matrix too

In [49]:
momo.elasticity.s.half_satured()

momo.elasticity.s.df

meta_1  meta_2
reaction_0    -0.5    -0.0
reaction_1     0.5    -0.5
reaction_2    -0.0     0.5

### To modify an elestacity coefficient, use the Pandas paradigme.

In [50]:
momo.elasticity.s.df.at["reaction_2", "meta_0"] = 2
momo.elasticity.s.df.loc["reaction_1"] = [-1 for i in range(momo.elasticity.s.df.shape[1])]

momo.elasticity.s.df

meta_1  meta_2  meta_0
reaction_0    -0.5    -0.0     NaN
reaction_1    -1.0    -1.0    -1.0
reaction_2    -0.0     0.5     2.0

# <font color='red'> [2] Post-simulation analysis </font> 

## <font color='green'> [2.0] Accessing the MCA coefficient </font> 

In [51]:
momo.Stoichio_matrix

reaction_0  reaction_1  reaction_2
meta_0          -1           0           0
meta_1           1          -1           0
meta_2           0           1          -1
meta_3           0           0           1

In [52]:
momo.elasticity.s.df

meta_1  meta_2  meta_0
reaction_0    -0.5    -0.0     NaN
reaction_1    -1.0    -1.0    -1.0
reaction_2    -0.0     0.5     2.0

In [53]:
momo.elasticity.p.df

Temperature  meta_0_para  meta_3_para  enzyme_reaction_0_para  \
reaction_0            0          0.5         -0.0                     1.0   
reaction_1            0         -0.0         -0.0                     0.0   
reaction_2            0         -0.0         -0.5                     0.0   

            enzyme_reaction_1_para  enzyme_reaction_2_para  
reaction_0                     0.0                     0.0  
reaction_1                     1.0                     0.0  
reaction_2                     0.0                     1.0

In [54]:
J = momo.Jacobian
J

[[ 1.00000000e+00 -3.33066907e-16]
 [ 2.77555756e-16  1.00000000e+00]]
[[ 1.00000000e+00 -3.33066907e-16]
 [ 2.77555756e-16  1.00000000e+00]]


meta_1  meta_2
meta_1     0.5     1.0
meta_2    -1.0    -1.5

In [55]:
J_inv = momo.Jacobian_reversed
J_inv

[[ 1.00000000e+00 -3.33066907e-16]
 [ 2.77555756e-16  1.00000000e+00]]
[[ 1.00000000e+00 -3.33066907e-16]
 [ 2.77555756e-16  1.00000000e+00]]
[[ 1.00000000e+00 -3.33066907e-16]
 [ 2.77555756e-16  1.00000000e+00]]


meta_1  meta_2
meta_1    -6.0    -4.0
meta_2     4.0     2.0

In [56]:
L = momo.Link_matrix[0]
print(f"Link matrix : \n{L}\n")
N_r = momo.Link_matrix[1]
print(f"Reduced N matrix :")
N_r

Link matrix : 
[[ 1.00000000e+00 -3.33066907e-16]
 [ 2.77555756e-16  1.00000000e+00]]

Reduced N matrix :


reaction_0  reaction_1  reaction_2
meta_1           1          -1           0
meta_2           0           1          -1

In [57]:
e_p = momo.elasticity.p.df.to_numpy()
e_p

array([[ 0. ,  0.5, -0. ,  1. ,  0. ,  0. ],
       [ 0. , -0. , -0. ,  0. ,  1. ,  0. ],
       [ 0. , -0. , -0.5,  0. ,  0. ,  1. ]])

In [58]:
C = -np.dot(np.dot(L, J_inv),N_r)
R_s_p = np.dot(C,e_p)

C

array([[ 6., -2., -4.],
       [-4.,  2.,  2.]])

In [59]:
momo.R_s_p

[[ 1.00000000e+00 -3.33066907e-16]
 [ 2.77555756e-16  1.00000000e+00]]


Temperature  meta_0_para  meta_3_para  enzyme_reaction_0_para  \
meta_1          0.0          3.0          2.0                     6.0   
meta_2          0.0         -2.0         -1.0                    -4.0   

        enzyme_reaction_1_para  enzyme_reaction_2_para  
meta_1                    -2.0                    -4.0  
meta_2                     2.0                     2.0

In [60]:
momo.R_v_p

Temperature  meta_0_para  meta_3_para  enzyme_reaction_0_para  \
reaction_0          0.0         -1.0         -1.0                    -2.0   
reaction_1          0.0         -1.0         -1.0                    -2.0   
reaction_2          0.0         -1.0         -1.0                    -2.0   

            enzyme_reaction_1_para  enzyme_reaction_2_para  
reaction_0                     1.0                     2.0  
reaction_1                     1.0                     2.0  
reaction_2                     1.0                     2.0

## <font color='green'> [2.1] Correlation and Mutual Information </font> 

### <font color='white'> [2.1.0] Correlation </font> 

In [61]:
momo.rho()

Temperature  meta_0_para  meta_3_para  \
Temperature                     1.0     0.000000     0.000000   
meta_0_para                     0.0     1.000000     0.000000   
meta_3_para                     0.0     0.000000     1.000000   
enzyme_reaction_0_para          0.0     0.000000     0.000000   
enzyme_reaction_1_para          0.0     0.000000     0.000000   
enzyme_reaction_2_para          0.0     0.000000     0.000000   
meta_1                          0.0     0.361158     0.240772   
meta_2                          0.0    -0.371391    -0.185695   
reaction_0                      0.0    -0.301511    -0.301511   
reaction_1                      0.0    -0.301511    -0.301511   
reaction_2                      0.0    -0.301511    -0.301511   

                        enzyme_reaction_0_para  enzyme_reaction_1_para  \
Temperature                           0.000000                0.000000   
meta_0_para                           0.000000                0.000000   
meta_3_para                           0.000000                0.000000   
enzyme_reaction_0_para                1.000000                0.000000   
enzyme_reaction_1_para                0.000000                1.000000   
enzyme_reaction_2_para                0.000000                0.000000   
meta_1                                0.722315               -0.240772   
meta_2                               -0.742781                0.371391   
reaction_0                           -0.603023                0.301511   
reaction_1                           -0.603023                0.301511   
reaction_2                           -0.603023                0.301511   

                        enzyme_reaction_2_para    meta_1    meta_2  \
Temperature                           0.000000  0.000000  0.000000   
meta_0_para                           0.000000  0.361158 -0.371391   
meta_3_para                           0.000000  0.240772 -0.185695   
enzyme_reaction_0_para                0.000000  0.722315 -0.742781   
enzyme_reaction_1_para                0.000000 -0.240772  0.371391   
enzyme_reaction_2_para                1.000000 -0.481543  0.371391   
meta_1                               -0.481543  1.000000 -0.983624   
meta_2                                0.371391 -0.983624  1.000000   
reaction_0                            0.603023 -0.980038  0.951817   
reaction_1                            0.603023 -0.980038  0.951817   
reaction_2                            0.603023 -0.980038  0.951817   

                        reaction_0  reaction_1  reaction_2  
Temperature               0.000000    0.000000    0.000000  
meta_0_para              -0.301511   -0.301511   -0.301511  
meta_3_para              -0.301511   -0.301511   -0.301511  
enzyme_reaction_0_para   -0.603023   -0.603023   -0.603023  
enzyme_reaction_1_para    0.301511    0.301511    0.301511  
enzyme_reaction_2_para    0.603023    0.603023    0.603023  
meta_1                   -0.980038   -0.980038   -0.980038  
meta_2                    0.951817    0.951817    0.951817  
reaction_0                1.000000    1.000000    1.000000  
reaction_1                1.000000    1.000000    1.000000  
reaction_2                1.000000    1.000000    1.000000

In [62]:
Cov = momo.rho()

In [63]:
Cov

Temperature  meta_0_para  meta_3_para  \
Temperature                     1.0     0.000000     0.000000   
meta_0_para                     0.0     1.000000     0.000000   
meta_3_para                     0.0     0.000000     1.000000   
enzyme_reaction_0_para          0.0     0.000000     0.000000   
enzyme_reaction_1_para          0.0     0.000000     0.000000   
enzyme_reaction_2_para          0.0     0.000000     0.000000   
meta_1                          0.0     0.361158     0.240772   
meta_2                          0.0    -0.371391    -0.185695   
reaction_0                      0.0    -0.301511    -0.301511   
reaction_1                      0.0    -0.301511    -0.301511   
reaction_2                      0.0    -0.301511    -0.301511   

                        enzyme_reaction_0_para  enzyme_reaction_1_para  \
Temperature                           0.000000                0.000000   
meta_0_para                           0.000000                0.000000   
meta_3_para                           0.000000                0.000000   
enzyme_reaction_0_para                1.000000                0.000000   
enzyme_reaction_1_para                0.000000                1.000000   
enzyme_reaction_2_para                0.000000                0.000000   
meta_1                                0.722315               -0.240772   
meta_2                               -0.742781                0.371391   
reaction_0                           -0.603023                0.301511   
reaction_1                           -0.603023                0.301511   
reaction_2                           -0.603023                0.301511   

                        enzyme_reaction_2_para    meta_1    meta_2  \
Temperature                           0.000000  0.000000  0.000000   
meta_0_para                           0.000000  0.361158 -0.371391   
meta_3_para                           0.000000  0.240772 -0.185695   
enzyme_reaction_0_para                0.000000  0.722315 -0.742781   
enzyme_reaction_1_para                0.000000 -0.240772  0.371391   
enzyme_reaction_2_para                1.000000 -0.481543  0.371391   
meta_1                               -0.481543  1.000000 -0.983624   
meta_2                                0.371391 -0.983624  1.000000   
reaction_0                            0.603023 -0.980038  0.951817   
reaction_1                            0.603023 -0.980038  0.951817   
reaction_2                            0.603023 -0.980038  0.951817   

                        reaction_0  reaction_1  reaction_2  
Temperature               0.000000    0.000000    0.000000  
meta_0_para              -0.301511   -0.301511   -0.301511  
meta_3_para              -0.301511   -0.301511   -0.301511  
enzyme_reaction_0_para   -0.603023   -0.603023   -0.603023  
enzyme_reaction_1_para    0.301511    0.301511    0.301511  
enzyme_reaction_2_para    0.603023    0.603023    0.603023  
meta_1                   -0.980038   -0.980038   -0.980038  
meta_2                    0.951817    0.951817    0.951817  
reaction_0                1.000000    1.000000    1.000000  
reaction_1                1.000000    1.000000    1.000000  
reaction_2                1.000000    1.000000    1.000000

### <font color='white'> [2.1.1] Mutual information </font> 

In [64]:
momo.group_MI()

Temperature  meta_0_para  meta_3_para  \
Temperature                     inf    -0.000000    -0.000000   
meta_0_para                    -0.0          inf    -0.000000   
meta_3_para                    -0.0    -0.000000          inf   
enzyme_reaction_0_para         -0.0    -0.000000    -0.000000   
enzyme_reaction_1_para         -0.0    -0.000000    -0.000000   
enzyme_reaction_2_para         -0.0    -0.000000    -0.000000   
meta_1                         -0.0     0.069881     0.029860   
meta_2                         -0.0     0.074210     0.017546   
reaction_0                     -0.0     0.047655     0.047655   
reaction_1                     -0.0     0.047655     0.047655   
reaction_2                     -0.0     0.047655     0.047655   

                        enzyme_reaction_0_para  enzyme_reaction_1_para  \
Temperature                          -0.000000               -0.000000   
meta_0_para                          -0.000000               -0.000000   
meta_3_para                          -0.000000               -0.000000   
enzyme_reaction_0_para                     inf               -0.000000   
enzyme_reaction_1_para               -0.000000                     inf   
enzyme_reaction_2_para               -0.000000               -0.000000   
meta_1                                0.368799                0.029860   
meta_2                                0.401173                0.074210   
reaction_0                            0.225993                0.047655   
reaction_1                            0.225993                0.047655   
reaction_2                            0.225993                0.047655   

                        enzyme_reaction_2_para    meta_1    meta_2  \
Temperature                          -0.000000 -0.000000 -0.000000   
meta_0_para                          -0.000000  0.069881  0.074210   
meta_3_para                          -0.000000  0.029860  0.017546   
enzyme_reaction_0_para               -0.000000  0.368799  0.401173   
enzyme_reaction_1_para               -0.000000  0.029860  0.074210   
enzyme_reaction_2_para                     inf  0.131907  0.074210   
meta_1                                0.131907       inf  1.713508   
meta_2                                0.074210  1.713508       inf   
reaction_0                            0.225993  1.615402  1.181997   
reaction_1                            0.225993  1.615402  1.181997   
reaction_2                            0.225993  1.615402  1.181997   

                        reaction_0  reaction_1  reaction_2  
Temperature              -0.000000   -0.000000   -0.000000  
meta_0_para               0.047655    0.047655    0.047655  
meta_3_para               0.047655    0.047655    0.047655  
enzyme_reaction_0_para    0.225993    0.225993    0.225993  
enzyme_reaction_1_para    0.047655    0.047655    0.047655  
enzyme_reaction_2_para    0.225993    0.225993    0.225993  
meta_1                    1.615402    1.615402    1.615402  
meta_2                    1.181997    1.181997    1.181997  
reaction_0                     inf         NaN         inf  
reaction_1                     NaN         inf   18.021827  
reaction_2                     inf   18.021827         inf

### <font color='white'> [2.1.2] Plot </font> 

In [65]:
import numpy as np
np.sqrt(2*np.pi*np.e*1)

4.132731354122493

In [66]:
momo.parameters.df

Mean values Standard deviation
Temperature                 273.15                1.0
meta_0_para                    1.0                1.0
meta_3_para                    1.0                1.0
enzyme_reaction_0_para         1.0                1.0
enzyme_reaction_1_para         1.0                1.0
enzyme_reaction_2_para         1.0                1.0

In [67]:
#momo.plot(result="MI", label=True, value_in_cell=False )

## <font color='green'> [2.2] Sampling </font> 

### <font color='white'> [2.2.0] Let's create an exemple </font> 

In [68]:
from main import MODEL

momo = MODEL()
momo.read_SBML()

momo.enzymes.add_to_all_reaction()
momo.parameters.add_externals()
momo.parameters.add_enzymes()

momo.elasticity.s.half_satured()

Model created 
 
To add metabolite, use .metabolites.add_meta 
To add reaction,   use .reactions.add_reaction
Model created 
 
To add metabolite, use .metabolites.add_meta 
To add reaction,   use .reactions.add_reaction
0 error detected in your SBML file


In [69]:
momo.elasticity.p.df

Temperature  D_Glucose_para  Orthophosphate_para  \
PTS_RPTSsy                0            -0.5                 -0.0   
PGI_R02740                0            -0.0                 -0.0   
PFK_R04779                0            -0.0                 -0.0   
ALD_R01070                0            -0.0                 -0.0   
TIM_R01015                0            -0.0                 -0.0   
GAP_R01061                0            -0.0                 -0.5   
PGK_R01512                0            -0.0                 -0.0   
PGM_R01518                0            -0.0                 -0.0   
PGH_R00658                0            -0.0                 -0.0   
PYK_R00200                0            -0.0                 -0.0   
PDH_R00209                0            -0.0                 -0.0   
ZWF_R00835                0            -0.0                 -0.0   
GLH_R02035                0            -0.0                 -0.0   
PGD_R01528                0            -0.0                 -0.0   
RPI_R01056                0            -0.0                 -0.0   
RPE_R01529                0            -0.0                 -0.0   
TXT_R01641                0            -0.0                 -0.0   
TAL_R08575                0            -0.0                 -0.0   
TXT_R01067                0            -0.0                 -0.0   
CSN_R00351                0            -0.0                 -0.0   
ACN_R01325                0            -0.0                 -0.0   
ACN_R01900                0            -0.0                 -0.0   
ICD_R00709                0            -0.0                 -0.0   
KGD_R08549                0            -0.0                 -0.0   
SCS_R00405                0            -0.0                 -0.5   
SDH_R02164                0            -0.0                 -0.0   
FUM_R01082                0            -0.0                 -0.0   
MDH_R00342                0            -0.0                 -0.0   
PPC_R00345                0            -0.0                 -0.5   
Overflow                  0            -0.0                 -0.0   
OxAConsumption            0            -0.0                 -0.0   

                NADPplus_para  NADPH_para  NADH_para  NADplus_para  ATP_para  \
PTS_RPTSsy               -0.0        -0.0       -0.0          -0.0      -0.0   
PGI_R02740               -0.0        -0.0       -0.0          -0.0      -0.0   
PFK_R04779               -0.0        -0.0       -0.0          -0.0      -0.5   
ALD_R01070               -0.0        -0.0       -0.0          -0.0      -0.0   
TIM_R01015               -0.0        -0.0       -0.0          -0.0      -0.0   
GAP_R01061               -0.0        -0.0       -0.5          -0.5      -0.0   
PGK_R01512               -0.0        -0.0       -0.0          -0.0      -0.5   
PGM_R01518               -0.0        -0.0       -0.0          -0.0      -0.0   
PGH_R00658               -0.0        -0.0       -0.0          -0.0      -0.0   
PYK_R00200               -0.0        -0.0       -0.0          -0.0      -0.5   
PDH_R00209               -0.0        -0.0       -0.5          -0.5      -0.0   
ZWF_R00835               -0.5        -0.5       -0.0          -0.0      -0.0   
GLH_R02035               -0.0        -0.0       -0.0          -0.0      -0.0   
PGD_R01528               -0.5        -0.5       -0.0          -0.0      -0.0   
RPI_R01056               -0.0        -0.0       -0.0          -0.0      -0.0   
RPE_R01529               -0.0        -0.0       -0.0          -0.0      -0.0   
TXT_R01641               -0.0        -0.0       -0.0          -0.0      -0.0   
TAL_R08575               -0.0        -0.0       -0.0          -0.0      -0.0   
TXT_R01067               -0.0        -0.0       -0.0          -0.0      -0.0   
CSN_R00351               -0.0        -0.0       -0.0          -0.0      -0.0   
ACN_R01325               -0.0        -0.0       -0.0          -0.0      -0.0   
ACN_R01900               -0.0        -0.0       -0.0          -0.0      -0.0   

In [70]:
print(f"Shape of the stoichio matrix : {momo.Stoichio_matrix.shape} \n")
print(f"numbers of metabolite in the model : {momo.metabolites.len} \n")
print(f"Numbers of reaction in the model : {momo.reactions.len} \n")
print(f"Numbers of enzyme in the model : {momo.enzymes.df.shape[0]} \n")
print(f"Numbers of parameters in the model : {momo.parameters.df.shape[0]} \n")

Shape of the stoichio matrix : (40, 31) 

numbers of metabolite in the model : 40 

Numbers of reaction in the model : 31 

Numbers of enzyme in the model : 31 

Numbers of parameters in the model : 44 



In [71]:
momo.R

[[ 1.00000000e+00  1.66533454e-16 -8.32667268e-17 -1.38777878e-17
  -1.66533454e-16  9.02056208e-17 -2.77555756e-17  8.32667268e-17
  -2.77555756e-17 -1.11022302e-16 -1.11022302e-16 -2.77555756e-17
  -5.55111512e-17  1.11022302e-16  0.00000000e+00 -2.77555756e-17
   1.38777878e-16 -1.11022302e-16  5.55111512e-17  1.11022302e-16
   0.00000000e+00  0.00000000e+00 -8.32667268e-17 -5.55111512e-17
   2.22044605e-16  1.38777878e-17 -8.32667268e-17]
 [ 1.11022302e-16  1.00000000e+00  4.02455846e-16 -1.94289029e-16
   2.22044605e-16  2.11636264e-16  5.55111512e-17  2.43728648e-16
  -4.16333634e-16 -2.77555756e-17  8.32667268e-17  3.60822483e-16
  -1.17961196e-16 -1.11022302e-16  3.33066907e-16  1.66533454e-16
  -1.38777878e-16  3.33066907e-16  6.24500451e-17 -2.77555756e-16
  -3.88578059e-16  1.11022302e-16 -4.30211422e-16 -2.91433544e-16
   1.66533454e-16 -3.64291930e-16  3.19189120e-16]
 [ 3.81639165e-16 -3.33066907e-16  1.00000000e+00  3.46944695e-16
   1.66533454e-16 -3.26128013e-16  2.532

Temperature  D_Glucose_para  \
Phosphoenolpyruvate                        0.0       -0.046328   
Pyruvate                                   0.0       -0.142816   
D_Glucose_6_phosphate                      0.0       -0.545184   
_S_Malate                                  0.0       -0.002688   
Acetyl_CoA                                 0.0        0.053535   
Fumarate                                   0.0       -0.007550   
cis_Aconitate                              0.0        0.058739   
_6_Phospho_D_gluconate                     0.0       -0.286433   
_2_Oxoglutarate                            0.0        0.038264   
Oxaloacetate                               0.0        0.012926   
D_Erythrose_4_phosphate                    0.0       -0.507378   
Isocitrate                                 0.0       -0.048501   
D_Ribulose_5_phosphate                     0.0        0.157058   
D_Xylulose_5_phosphate                     0.0       -0.070808   
_3_Phospho_D_glyceroyl_phosphate           0.0       -0.083047   
CoA                                        0.0        0.012755   
D_Ribose_5_phosphate                       0.0       -0.113933   
Glycerone_phosphate                        0.0        0.010124   
D_Fructose_1_6_bisphosphate                0.0       -0.272592   
D_Glyceraldehyde_3_phosphate               0.0        0.126173   
Citrate                                    0.0       -0.068977   
Succinyl_CoA                               0.0       -0.040780   
_3_Phospho_D_glycerate                     0.0        0.039922   
D_Glucono_1_5_lactone_6_phosphate          0.0        0.415809   
D_Fructose_6_phosphate                     0.0        0.408888   
_2_Phospho_D_glycerate                     0.0        0.003203   
Succinate                                  0.0        0.017788   
Sedoheptulose_7_phosphate                  0.0        0.015443   
PTS_RPTSsy                                 0.0       -0.132836   
PGI_R02740                                 0.0        0.068148   
PFK_R04779                                 0.0       -0.068148   
ALD_R01070                                 0.0        0.068148   
TIM_R01015                                 0.0       -0.068148   
GAP_R01061                                 0.0       -0.021563   
PGK_R01512                                 0.0        0.021563   
PGM_R01518                                 0.0       -0.021563   
PGH_R00658                                 0.0        0.021563   
PYK_R00200                                 0.0        0.094572   
PDH_R00209                                 0.0        0.038264   
ZWF_R00835                                 0.0        0.064688   
GLH_R02035                                 0.0       -0.064688   
PGD_R01528                                 0.0        0.064688   
RPI_R01056                                 0.0       -0.021563   
RPE_R01529                                 0.0       -0.043125   
TXT_R01641                                 0.0        0.021563   
TAL_R08575                                 0.0       -0.021563   
TXT_R01067                                 0.0        0.021563   
CSN_R00351                                 0.0       -0.005119   
ACN_R01325                                 0.0        0.005119   
ACN_R01900                                 0.0       -0.005119   
ICD_R00709                                 0.0        0.005119   
KGD_R08549                                 0.0       -0.005119   
SCS_R00405                                 0.0        0.005119   
SDH_R02164                                 0.0       -0.005119   
FUM_R01082                                 0.0        0.005119   
MDH_R00342                                 0.0       -0.005119   
PPC_R00345                                 0.0        0.016701   
Overflow                                   0.0       -0.033145   
OxAConsumption                             0.0       -0.006463   

                                   Orthophosphate_para  NADPplus_para  \
P

### <font color='white'> [2.2.1] Updating the dataframe of the sampling data </font> 

In [72]:
momo.data_sampling

Empty DataFrame
Columns: [Name, Type, Mean, Standard deviation, Distribution]
Index: []

In [73]:
momo.add_sampling_data(["PTS_RPTSsy","enzyme_PTS_RPTSsy_para"], "elasticity_p", mean = True)

momo.data_sampling

Name          Type  Mean  \
0  [PTS_RPTSsy, enzyme_PTS_RPTSsy_para]  elasticity_p   1.0   

   Standard deviation Distribution  
0                   1      uniform

### <font color='white'> [2.2.2] Launching the sampling loop </font> 

In [74]:
#import cProfile
#cProfile.run("momo.MI()")

In [75]:
momo.sampling(10, result='rho', seed_constant=False)

running time of the code : 0.2754809856414795 
So 0.02754809856414795 per occurences !


array([[ 1.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        , ...,  0.02808101,
        -0.05789336, -0.0095858 ],
       [ 0.        ,  0.        ,  1.        , ..., -0.24638198,
         0.12063197,  0.02061372],
       ...,
       [ 0.        ,  0.02808101, -0.24638198, ...,  1.        ,
        -0.82692539, -0.53862775],
       [ 0.        , -0.05789336,  0.12063197, ..., -0.82692539,
         1.        ,  0.84143604],
       [ 0.        , -0.0095858 ,  0.02061372, ..., -0.53862775,
         0.84143604,  1.        ]])

In [76]:
momo.group_MI([["enzyme_PTS_RPTSsy_para","enzyme_PGI_R02740_para"],["FUM_R01082","MDH_R00342"],["PPC_R00345"]])

[[ 1.00000000e+00  1.66533454e-16 -8.32667268e-17 -1.38777878e-17
  -1.66533454e-16  9.02056208e-17 -2.77555756e-17  8.32667268e-17
  -2.77555756e-17 -1.11022302e-16 -1.11022302e-16 -2.77555756e-17
  -5.55111512e-17  1.11022302e-16  0.00000000e+00 -2.77555756e-17
   1.38777878e-16 -1.11022302e-16  5.55111512e-17  1.11022302e-16
   0.00000000e+00  0.00000000e+00 -8.32667268e-17 -5.55111512e-17
   2.22044605e-16  1.38777878e-17 -8.32667268e-17]
 [ 1.11022302e-16  1.00000000e+00  4.02455846e-16 -1.94289029e-16
   2.22044605e-16  2.11636264e-16  5.55111512e-17  2.43728648e-16
  -4.16333634e-16 -2.77555756e-17  8.32667268e-17  3.60822483e-16
  -1.17961196e-16 -1.11022302e-16  3.33066907e-16  1.66533454e-16
  -1.38777878e-16  3.33066907e-16  6.24500451e-17 -2.77555756e-16
  -3.88578059e-16  1.11022302e-16 -4.30211422e-16 -2.91433544e-16
   1.66533454e-16 -3.64291930e-16  3.19189120e-16]
 [ 3.81639165e-16 -3.33066907e-16  1.00000000e+00  3.46944695e-16
   1.66533454e-16 -3.26128013e-16  2.532

0         1         2
0       inf       inf  0.004126
1  0.000884       inf  0.076872
2  0.004126  0.076872       inf

In [77]:
from main import *
momo = MODEL()
momo.read_SBML()

momo.elasticity.s.half_satured()
momo.enzymes.add_to_all_reaction()
momo.parameters.add_enzymes()
momo.parameters.add_externals()

Model created 
 
To add metabolite, use .metabolites.add_meta 
To add reaction,   use .reactions.add_reaction
Model created 
 
To add metabolite, use .metabolites.add_meta 
To add reaction,   use .reactions.add_reaction
0 error detected in your SBML file


In [78]:
a = momo.group_MI()

print(a.index[59])
a.loc[a.index[59]]

[[ 1.00000000e+00  1.66533454e-16 -8.32667268e-17 -1.38777878e-17
  -1.66533454e-16  9.02056208e-17 -2.77555756e-17  8.32667268e-17
  -2.77555756e-17 -1.11022302e-16 -1.11022302e-16 -2.77555756e-17
  -5.55111512e-17  1.11022302e-16  0.00000000e+00 -2.77555756e-17
   1.38777878e-16 -1.11022302e-16  5.55111512e-17  1.11022302e-16
   0.00000000e+00  0.00000000e+00 -8.32667268e-17 -5.55111512e-17
   2.22044605e-16  1.38777878e-17 -8.32667268e-17]
 [ 1.11022302e-16  1.00000000e+00  4.02455846e-16 -1.94289029e-16
   2.22044605e-16  2.11636264e-16  5.55111512e-17  2.43728648e-16
  -4.16333634e-16 -2.77555756e-17  8.32667268e-17  3.60822483e-16
  -1.17961196e-16 -1.11022302e-16  3.33066907e-16  1.66533454e-16
  -1.38777878e-16  3.33066907e-16  6.24500451e-17 -2.77555756e-16
  -3.88578059e-16  1.11022302e-16 -4.30211422e-16 -2.91433544e-16
   1.66533454e-16 -3.64291930e-16  3.19189120e-16]
 [ 3.81639165e-16 -3.33066907e-16  1.00000000e+00  3.46944695e-16
   1.66533454e-16 -3.26128013e-16  2.532

Temperature              -0.000000
enzyme_PTS_RPTSsy_para    0.000255
enzyme_PGI_R02740_para    0.000027
enzyme_PFK_R04779_para    0.000027
enzyme_ALD_R01070_para    0.000027
                            ...   
FUM_R01082                0.007589
MDH_R00342                0.007589
PPC_R00345                0.000052
Overflow                  0.000600
OxAConsumption            0.005298
Name: CoA, Length: 103, dtype: float64

In [79]:
momo.parameters.remove("Temperature")

Name of the removed parameter : Temperature


In [80]:
momo.group_entropy_fixed_vector()

[[ 1.00000000e+00  1.66533454e-16 -8.32667268e-17 -1.38777878e-17
  -1.66533454e-16  9.02056208e-17 -2.77555756e-17  8.32667268e-17
  -2.77555756e-17 -1.11022302e-16 -1.11022302e-16 -2.77555756e-17
  -5.55111512e-17  1.11022302e-16  0.00000000e+00 -2.77555756e-17
   1.38777878e-16 -1.11022302e-16  5.55111512e-17  1.11022302e-16
   0.00000000e+00  0.00000000e+00 -8.32667268e-17 -5.55111512e-17
   2.22044605e-16  1.38777878e-17 -8.32667268e-17]
 [ 1.11022302e-16  1.00000000e+00  4.02455846e-16 -1.94289029e-16
   2.22044605e-16  2.11636264e-16  5.55111512e-17  2.43728648e-16
  -4.16333634e-16 -2.77555756e-17  8.32667268e-17  3.60822483e-16
  -1.17961196e-16 -1.11022302e-16  3.33066907e-16  1.66533454e-16
  -1.38777878e-16  3.33066907e-16  6.24500451e-17 -2.77555756e-16
  -3.88578059e-16  1.11022302e-16 -4.30211422e-16 -2.91433544e-16
   1.66533454e-16 -3.64291930e-16  3.19189120e-16]
 [ 3.81639165e-16 -3.33066907e-16  1.00000000e+00  3.46944695e-16
   1.66533454e-16 -3.26128013e-16  2.532

0
0 -inf

# Test Part