# <font color='red'> [0] Build the model </font> 

## <font color='green'> [0.1] Importation of the package </font> 

In [1]:
from main import *

## <font color='green'> [0.2] Creation of an empty model </font> 

In [2]:
momo = model()

Model created 
 
To add metabolite, use .metabolites.add_meta 
To add reaction,   use .reactions.add_reaction


## <font color='green'> [0.3] Add of reaction and metabolite </font> 

In [3]:
momo.metabolites.add(name = "H2O", external = True, concentration = 1.0)

metabolite_reaction = {"H2O" : 1.0,
                       "H2"  :-1.0,
                       "O2"  :-0.5}

momo.reactions.add(name = "combustion", metabolites = metabolite_reaction, k_eq = 1.0, law = "", flux=1.0)

Don't worry, the metabolite will be add after the add of the 1st reaction
The metabolite "H2O" is already in the model !


In [4]:
metabolite_reaction2 = {"H2O" : -1.0,
                       "H2"  : 0.5,
                       "O2"  : 0.5}
momo.reactions.add(name = "test", metabolites = metabolite_reaction2, k_eq = 1.0, law = "", flux=1.0)

In [5]:
momo.reactions.df

Metabolites  Equilibrium constant Law  \
combustion  {'H2O': 1.0, 'H2': -1.0, 'O2': -0.5}                   1.0       
test         {'H2O': -1.0, 'H2': 0.5, 'O2': 0.5}                   1.0       

            Flux (mmol/gDW/h)  
combustion                  1  
test                        1

#### Add a reaction with specified metabolite and stoichiometric coefficient automaticaly adds them to the model

In [6]:
momo.metabolites.df

External  Concentration (mmol/gDW)
H2O     False                         1
H2      False                         1
O2      False                         1

#### Print the stoichiometric matrix

In [7]:
momo.Stoichio_matrix

combustion  test
H2O         1.0  -1.0
H2         -1.0   0.5
O2         -0.5   0.5

#### It is also possible to remove a metabolite or a reaction to the model

In [8]:
momo.metabolites.remove("O2")
momo.metabolites.df

External  Concentration (mmol/gDW)
H2O     False                         1
H2      False                         1

#### Removing a metabolite remove also every mention of it in the reactions dataframe and in the stoichiometric matrix

In [9]:
momo.reactions.df

Metabolites  Equilibrium constant Law  \
combustion  {'H2O': 1.0, 'H2': -1.0}                   1.0       
test        {'H2O': -1.0, 'H2': 0.5}                   1.0       

            Flux (mmol/gDW/h)  
combustion                  1  
test                        1

In [10]:
momo.Stoichio_matrix

combustion  test
H2O         1.0  -1.0
H2         -1.0   0.5

In [11]:
momo.reactions.remove(name="combustion")
momo.reactions.df

Metabolites  Equilibrium constant Law  Flux (mmol/gDW/h)
test  {'H2O': -1.0, 'H2': 0.5}                   1.0                      1

## <font color='green'> [0.4] Stoichiometric matrix from an existant one </font> 

In [12]:
reactions = {'Combustion': [1. , -1., -0.5],
            'Reaction_2': [0. ,  0.,   0. ]}

metabolites = ['H2O', 'H2', 'O2']

dataframe = pd.DataFrame(reactions, index=metabolites)

momo.Stoichio_matrix = dataframe

#### And the metabolites and reactions dataframes are automatically update

In [13]:
momo.Stoichio_matrix

Combustion  Reaction_2
H2O         1.0         0.0
H2         -1.0         0.0
O2         -0.5         0.0

In [14]:
momo.reactions.df

Metabolites  Equilibrium constant Law  \
Combustion  {'H2O': 1.0, 'H2': -1.0, 'O2': -0.5}                   1.0       
Reaction_2                                    {}                   1.0       

            Flux (mmol/gDW/h)  
Combustion                  1  
Reaction_2                  1

In [15]:
momo.metabolites.df

External  Concentration (mmol/gDW)
H2O     False                         1
H2      False                         1
O2      False                         1

## <font color='green'> [0.5] Create a linear system </font> 

In [16]:
momo.creat_linear(4)

Model created 
 
To add metabolite, use .metabolites.add_meta 
To add reaction,   use .reactions.add_reaction


### Display the variables of the system

In [17]:
momo.metabolites.df

External  Concentration (mmol/gDW)
meta_0      True                         1
meta_1     False                         1
meta_2     False                         1
meta_3      True                         1

In [18]:
momo.reactions.df

Metabolites  Equilibrium constant Law  \
reaction_0  {'meta_0': -1, 'meta_1': 1}                   1.0       
reaction_1  {'meta_1': -1, 'meta_2': 1}                   1.0       
reaction_2  {'meta_2': -1, 'meta_3': 1}                   1.0       

            Flux (mmol/gDW/h)  
reaction_0                  1  
reaction_1                  1  
reaction_2                  1

## <font color='green'> [0.6] Read a CSV file </font> 

In [19]:
momo.read_CSV()

In [20]:
momo.Stoichio_matrix

ACALD ACALDt ACKr ACONTa ACONTb ACt2r ADK1 AKGDH AKGt2r ALCD2x  ...  \
13dpg       0      0    0      0      0     0    0     0      0      0  ...   
2pg         0      0    0      0      0     0    0     0      0      0  ...   
3pg         0      0    0      0      0     0    0     0      0      0  ...   
6pgc        0      0    0      0      0     0    0     0      0      0  ...   
6pgl        0      0    0      0      0     0    0     0      0      0  ...   
...       ...    ...  ...    ...    ...   ...  ...   ...    ...    ...  ...   
s7p         0      0    0      0      0     0    0     0      0      0  ...   
succ        0      0    0      0      0     0    0     0      0      0  ...   
succ(e)     0      0    0      0      0     0    0     0      0      0  ...   
succoa      0      0    0      0      0     0    0     1      0      0  ...   
xu5p-D      0      0    0      0      0     0    0     0      0      0  ...   

        RPI SUCCt2_2 SUCCt3 SUCDi SUCOAS TALA THD2 TKT1 TKT2 TPI  
13dpg     0        0      0     0      0    0    0    0    0   0  
2pg       0        0      0     0      0    0    0    0    0   0  
3pg       0        0      0     0      0    0    0    0    0   0  
6pgc      0        0      0     0      0    0    0    0    0   0  
6pgl      0        0      0     0      0    0    0    0    0   0  
...      ..      ...    ...   ...    ...  ...  ...  ...  ...  ..  
s7p       0        0      0     0      0   -1    0    1    0   0  
succ      0        1     -1    -1     -1    0    0    0    0   0  
succ(e)   0       -1      1     0      0    0    0    0    0   0  
succoa    0        0      0     0      1    0    0    0    0   0  
xu5p-D    0        0      0     0      0    0    0   -1   -1   0  

[72 rows x 95 columns]

## <font color='green'> [0.7] Read a SBML file </font> 

In [21]:
from main import *
momo = model()
momo.read_SBML()

momo.elasticity.s.half_satured()

Model created 
 
To add metabolite, use .metabolites.add_meta 
To add reaction,   use .reactions.add_reaction
Model created 
 
To add metabolite, use .metabolites.add_meta 
To add reaction,   use .reactions.add_reaction
0 error detected in your SBML file


Here, a warning occurs because one of the metabolite of the refence state file isn't in the main SBML file ( "_S__Malate" insteed of "_S_Malate" )

# <font color='red'> [1] Play with the variables </font> 

In [22]:
momo.creat_linear(4)

Model created 
 
To add metabolite, use .metabolites.add_meta 
To add reaction,   use .reactions.add_reaction


In [23]:
momo.elasticity.s.df

meta_0  meta_1  meta_2  meta_3
reaction_0       0       0       0       0
reaction_1       0       0       0       0
reaction_2       0       0       0       0

In [24]:
momo.parameters.add_externals()

In [25]:
momo.elasticity.p.df

Temperature  meta_0_para  meta_3_para
reaction_0          0.0          0.5         -0.0
reaction_1          0.0         -0.0         -0.0
reaction_2          0.0         -0.0         -0.5

## <font color='green'> [1.1] Display the data </font> 

### <font color='white'> [1.1.1] Display the stoichiometric matrix </font> 

In [26]:
momo.Stoichio_matrix

reaction_0  reaction_1  reaction_2
meta_0          -1           0           0
meta_1           1          -1           0
meta_2           0           1          -1
meta_3           0           0           1

### <font color='white'> [1.1.2] Display the metabolite dataframe </font> 

In [27]:
momo.metabolites.df

External  Concentration (mmol/gDW)
meta_0      True                         1
meta_1     False                         1
meta_2     False                         1
meta_3      True                         1

### <font color='white'> [1.1.3] Display the reactions dataframe </font> 

In [28]:
momo.reactions.df

Metabolites  Equilibrium constant Law  \
reaction_0  {'meta_0': -1, 'meta_1': 1}                   1.0       
reaction_1  {'meta_1': -1, 'meta_2': 1}                   1.0       
reaction_2  {'meta_2': -1, 'meta_3': 1}                   1.0       

            Flux (mmol/gDW/h)  
reaction_0                  1  
reaction_1                  1  
reaction_2                  1

### <font color='white'> [1.1.4] Display the enzymes dataframe </font> 

In [29]:
momo.enzymes.df

Empty DataFrame
Columns: [Concentration / Activity, Reactions linked]
Index: []

### <font color='white'> [1.1.5] Display the elasticities matrices </font> 

In [30]:
momo.elasticity.s.df

meta_0  meta_1  meta_2  meta_3
reaction_0       0       0       0       0
reaction_1       0       0       0       0
reaction_2       0       0       0       0

In [31]:
momo.elasticity.p

            Temperature  meta_0_para  meta_3_para
reaction_0          0.0          0.5         -0.0
reaction_1          0.0         -0.0         -0.0
reaction_2          0.0         -0.0         -0.5

### <font color='white'> [1.1.6] Display the enzymes dataframes </font> 

In [32]:
momo.enzymes.df

Empty DataFrame
Columns: [Concentration / Activity, Reactions linked]
Index: []

## <font color='green'> [1.2] Enzymes </font> 

#### The enzyme dataframe is initially empty

### <font color='white'> [1.2.1] Add enzymes linked to each reactions </font> 

In [33]:
momo.enzymes.add_to_all_reaction()

In [34]:
momo.enzymes.df

Concentration / Activity Reactions linked
enzyme_reaction_0                         1     [reaction_0]
enzyme_reaction_1                         1     [reaction_1]
enzyme_reaction_2                         1     [reaction_2]

### <font color='white'> [1.2.1] Add a specific enzyme </font> 

In [35]:
momo.enzymes.add(name = "name_enzyme", mean = 1.0, reaction_linked = ["PTS_RPTSsy", "PGI_R02740", "PFK_R04779"])

### <font color='white'> [1.2.1] Remove a specific enzyme </font> 

In [36]:
momo.enzymes.remove(name = "name_enzyme")

But on this state, the enzymes hasn't any influence on our study, we have to consider our enzyme as a parameters to create a elasticity between it and flux

## <font color='green'> [1.3] Parameters </font> 

### Adding a new parameters automatcally update the E_p elasticiy matix by adding a new column

There is only the temperture by default in the parameters dataframe

In [37]:
momo.parameters.df

Mean values Standard deviation
Temperature      273.15                1.0
meta_0_para         1.0                1.0
meta_3_para         1.0                1.0

### <font color='white'> [1.3.1] Add a specific parameter one by one </font> 

In [38]:
momo.parameters.add(name = "name_parameter", mean = 1.0, Standard_deviation = 0.5)

### <font color='white'> [1.3.2] Removing a specific parameter </font> 

In [39]:
momo.parameters.remove(name = "name_parameter")

Name of the removed parameter : name_parameter


### <font color='white'> [1.3.3] Add every externals metabolite as parameters </font> 

In [40]:
momo.elasticity.p.df

Temperature  meta_0_para  meta_3_para
reaction_0          0.0          0.5         -0.0
reaction_1          0.0         -0.0         -0.0
reaction_2          0.0         -0.0         -0.5

In [41]:
momo.parameters.add_externals()

In [42]:
momo.elasticity.p.df

Temperature  meta_0_para  meta_3_para
reaction_0          0.0          0.5         -0.0
reaction_1          0.0         -0.0         -0.0
reaction_2          0.0         -0.0         -0.5

In [43]:
momo.parameters.df

Mean values Standard deviation
Temperature      273.15                1.0
meta_0_para         1.0                1.0
meta_3_para         1.0                1.0

##### And the enzymes too

### <font color='white'> [1.3.4] Add every enzymes as parameters </font> 

In [44]:
momo.parameters.add_enzymes()

In [45]:
momo.parameters.df

Mean values Standard deviation
Temperature                 273.15                1.0
meta_0_para                    1.0                1.0
meta_3_para                    1.0                1.0
enzyme_reaction_0_para         1.0                1.0
enzyme_reaction_1_para         1.0                1.0
enzyme_reaction_2_para         1.0                1.0

## <font color='green'> [1.4] Elasticities </font> 

#### When the .add_externals() and .add_enzymes() are call, it automatically add default values considering the link in the dataframe

In [46]:
momo.elasticity.p.df

Temperature  meta_0_para  meta_3_para  enzyme_reaction_0_para  \
reaction_0          0.0          0.5         -0.0                     1.0   
reaction_1          0.0         -0.0         -0.0                     0.0   
reaction_2          0.0         -0.0         -0.5                     0.0   

            enzyme_reaction_1_para  enzyme_reaction_2_para  
reaction_0                     0.0                     0.0  
reaction_1                     1.0                     0.0  
reaction_2                     0.0                     1.0

In [47]:
momo.elasticity.s.df

meta_0  meta_1  meta_2  meta_3
reaction_0       0       0       0       0
reaction_1       0       0       0       0
reaction_2       0       0       0       0

#### We can add default value to the E_s matrix too

In [48]:
momo.elasticity.s.half_satured()

momo.elasticity.s.df

meta_0  meta_1  meta_2  meta_3
reaction_0     0.5    -0.5    -0.0    -0.0
reaction_1    -0.0     0.5    -0.5    -0.0
reaction_2    -0.0    -0.0     0.5    -0.5

### To modify an elestacity coefficient, use the Pandas paradigme.

In [49]:
momo.elasticity.s.df.at["reaction_2", "meta_0"] = 2
momo.elasticity.s.df.loc["reaction_1"] = [-1 for i in range(momo.elasticity.s.df.shape[1])]

momo.elasticity.s.df

meta_0  meta_1  meta_2  meta_3
reaction_0     0.5    -0.5    -0.0    -0.0
reaction_1    -1.0    -1.0    -1.0    -1.0
reaction_2     2.0    -0.0     0.5    -0.5

# <font color='red'> [2] Post-simulation analysis </font> 

## <font color='green'> [2.0] Accessing the MCA coefficient </font> 

In [50]:
momo.Stoichio_matrix

reaction_0  reaction_1  reaction_2
meta_0          -1           0           0
meta_1           1          -1           0
meta_2           0           1          -1
meta_3           0           0           1

In [51]:
momo.elasticity.s.df

meta_0  meta_1  meta_2  meta_3
reaction_0     0.5    -0.5    -0.0    -0.0
reaction_1    -1.0    -1.0    -1.0    -1.0
reaction_2     2.0    -0.0     0.5    -0.5

In [52]:
momo.elasticity.p.df

Temperature  meta_0_para  meta_3_para  enzyme_reaction_0_para  \
reaction_0          0.0          0.5         -0.0                     1.0   
reaction_1          0.0         -0.0         -0.0                     0.0   
reaction_2          0.0         -0.0         -0.5                     0.0   

            enzyme_reaction_1_para  enzyme_reaction_2_para  
reaction_0                     0.0                     0.0  
reaction_1                     1.0                     0.0  
reaction_2                     0.0                     1.0

In [53]:
J = momo.Jacobian
J

meta_0  meta_1  meta_2
meta_0    -0.5     0.5     0.0
meta_1     0.5    -0.5     0.0
meta_2    -2.5    -0.5    -1.0

In [54]:
J_inv = momo.Jacobian_reversed
J_inv

meta_0    meta_1    meta_2
meta_0 -0.227273  0.227273 -0.272727
meta_1  0.772727 -0.772727 -0.272727
meta_2  0.181818 -0.181818 -0.181818

In [55]:
L = momo.Link_matrix[0]
print(f"Link matrix : \n{L}\n")
N_r = momo.Link_matrix[1]
print(f"Reduced N matrix :")
N_r

Link matrix : 
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [-1. -1. -1.]]

Reduced N matrix :


reaction_0  reaction_1  reaction_2
meta_0          -1           0           0
meta_1           1          -1           0
meta_2           0           1          -1

In [56]:
e_p = momo.elasticity.p.df.to_numpy()
e_p

array([[ 0. ,  0.5, -0. ,  1. ,  0. ,  0. ],
       [ 0. , -0. , -0. ,  0. ,  1. ,  0. ],
       [ 0. , -0. , -0.5,  0. ,  0. ,  1. ]])

In [57]:
C = -np.dot(np.dot(L, J_inv),N_r)
R_s_p = np.dot(C,e_p)

C

array([[-4.54545455e-01,  5.00000000e-01, -2.72727273e-01],
       [ 1.54545455e+00, -5.00000000e-01, -2.72727273e-01],
       [ 3.63636364e-01, -5.55111512e-17, -1.81818182e-01],
       [-1.45454545e+00,  2.22044605e-16,  7.27272727e-01]])

In [58]:
momo.R_s_p

Temperature  meta_0_para  meta_3_para  enzyme_reaction_0_para  \
meta_0          0.0    -0.227273     0.136364               -0.454545   
meta_1          0.0     0.772727     0.136364                1.545455   
meta_2          0.0     0.181818     0.090909                0.363636   
meta_3          0.0    -0.727273    -0.363636               -1.454545   

        enzyme_reaction_1_para  enzyme_reaction_2_para  
meta_0            5.000000e-01               -0.272727  
meta_1           -5.000000e-01               -0.272727  
meta_2           -5.551115e-17               -0.181818  
meta_3            2.220446e-16                0.727273

In [59]:
momo.R_v_p

Temperature   meta_0_para   meta_3_para  enzyme_reaction_0_para  \
reaction_0          0.0  2.220446e-16  4.163336e-17            4.440892e-16   
reaction_1          0.0 -1.110223e-16  0.000000e+00           -2.220446e-16   
reaction_2          0.0  2.775558e-16 -2.220446e-16            5.551115e-16   

            enzyme_reaction_1_para  enzyme_reaction_2_para  
reaction_0                     0.5           -8.326673e-17  
reaction_1                     1.0            0.000000e+00  
reaction_2                     1.0            4.440892e-16

## <font color='green'> [2.1] Correlation and Mutual Information </font> 

### <font color='white'> [2.1.0] Correlation </font> 

In [60]:
momo.rho()

Temperature   meta_0_para   meta_3_para  \
Temperature                     1.0  0.000000e+00  0.000000e+00   
meta_0_para                     0.0  1.000000e+00  0.000000e+00   
meta_3_para                     0.0  0.000000e+00  1.000000e+00   
enzyme_reaction_0_para          0.0  0.000000e+00  0.000000e+00   
enzyme_reaction_1_para          0.0  0.000000e+00  0.000000e+00   
enzyme_reaction_2_para          0.0  0.000000e+00  0.000000e+00   
meta_0                          0.0 -2.931052e-01  1.758631e-01   
meta_1                          0.0  4.235466e-01  7.474351e-02   
meta_2                          0.0  4.000000e-01  2.000000e-01   
meta_3                          0.0 -4.000000e-01 -2.000000e-01   
reaction_0                      0.0  4.440892e-16  8.326673e-17   
reaction_1                      0.0 -1.110223e-16  0.000000e+00   
reaction_2                      0.0  2.775558e-16 -2.220446e-16   

                        enzyme_reaction_0_para  enzyme_reaction_1_para  \
Temperature                       0.000000e+00            0.000000e+00   
meta_0_para                       0.000000e+00            0.000000e+00   
meta_3_para                       0.000000e+00            0.000000e+00   
enzyme_reaction_0_para            1.000000e+00            0.000000e+00   
enzyme_reaction_1_para            0.000000e+00            1.000000e+00   
enzyme_reaction_2_para            0.000000e+00            0.000000e+00   
meta_0                           -5.862104e-01            6.448314e-01   
meta_1                            8.470931e-01           -2.740595e-01   
meta_2                            8.000000e-01           -1.221245e-16   
meta_3                           -8.000000e-01            1.221245e-16   
reaction_0                        8.881784e-16            1.000000e+00   
reaction_1                       -2.220446e-16            1.000000e+00   
reaction_2                        5.551115e-16            1.000000e+00   

                        enzyme_reaction_2_para    meta_0    meta_1  \
Temperature                       0.000000e+00  0.000000  0.000000   
meta_0_para                       0.000000e+00 -0.293105  0.423547   
meta_3_para                       0.000000e+00  0.175863  0.074744   
enzyme_reaction_0_para            0.000000e+00 -0.586210  0.847093   
enzyme_reaction_1_para            0.000000e+00  0.644831 -0.274060   
enzyme_reaction_2_para            1.000000e+00 -0.351726 -0.149487   
meta_0                           -3.517262e-01  1.000000 -0.731718   
meta_1                           -1.494870e-01 -0.731718  1.000000   
meta_2                           -4.000000e-01 -0.410347  0.921837   
meta_3                            4.000000e-01  0.410347 -0.921837   
reaction_0                       -1.665335e-16  0.644831 -0.274060   
reaction_1                        0.000000e+00  0.644831 -0.274060   
reaction_2                        4.440892e-16  0.644831 -0.274060   

                              meta_2        meta_3    reaction_0  \
Temperature             0.000000e+00  0.000000e+00  0.000000e+00   
meta_0_para             4.000000e-01 -4.000000e-01  4.440892e-16   
meta_3_para             2.000000e-01 -2.000000e-01  8.326673e-17   
enzyme_reaction_0_para  8.000000e-01 -8.000000e-01  8.881784e-16   
enzyme_reaction_1_para -1.221245e-16  1.221245e-16  1.000000e+00   
enzyme_reaction_2_para -4.000000e-01  4.000000e-01 -1.665335e-16   
meta_0                 -4.103473e-01  4.103473e-01  6.448314e-01   
meta_1                  9.218366e-01 -9.218366e-01 -2.740595e-01   
meta_2                  1.000000e+00 -1.000000e+00  8.493206e-16   
meta_3                 -1.000000e+00  1.000000e+00 -8.493206e-16   
reaction_0              8.493206e-16 -8.493206e-16  1.000000e+00   
reaction_1             -3.441691e-16  3.441691e-16  1.000000e+00   
reaction_2              2.109424e-16 -2.109424e-16  1.000000e+00   

                          reaction_1    reaction_2  
Temperature             0.000000e+00  0.000000e+00  
meta_0_p

In [61]:
Cov = momo.rho()

In [62]:
Cov

Temperature   meta_0_para   meta_3_para  \
Temperature                     1.0  0.000000e+00  0.000000e+00   
meta_0_para                     0.0  1.000000e+00  0.000000e+00   
meta_3_para                     0.0  0.000000e+00  1.000000e+00   
enzyme_reaction_0_para          0.0  0.000000e+00  0.000000e+00   
enzyme_reaction_1_para          0.0  0.000000e+00  0.000000e+00   
enzyme_reaction_2_para          0.0  0.000000e+00  0.000000e+00   
meta_0                          0.0 -2.931052e-01  1.758631e-01   
meta_1                          0.0  4.235466e-01  7.474351e-02   
meta_2                          0.0  4.000000e-01  2.000000e-01   
meta_3                          0.0 -4.000000e-01 -2.000000e-01   
reaction_0                      0.0  4.440892e-16  8.326673e-17   
reaction_1                      0.0 -1.110223e-16  0.000000e+00   
reaction_2                      0.0  2.775558e-16 -2.220446e-16   

                        enzyme_reaction_0_para  enzyme_reaction_1_para  \
Temperature                       0.000000e+00            0.000000e+00   
meta_0_para                       0.000000e+00            0.000000e+00   
meta_3_para                       0.000000e+00            0.000000e+00   
enzyme_reaction_0_para            1.000000e+00            0.000000e+00   
enzyme_reaction_1_para            0.000000e+00            1.000000e+00   
enzyme_reaction_2_para            0.000000e+00            0.000000e+00   
meta_0                           -5.862104e-01            6.448314e-01   
meta_1                            8.470931e-01           -2.740595e-01   
meta_2                            8.000000e-01           -1.221245e-16   
meta_3                           -8.000000e-01            1.221245e-16   
reaction_0                        8.881784e-16            1.000000e+00   
reaction_1                       -2.220446e-16            1.000000e+00   
reaction_2                        5.551115e-16            1.000000e+00   

                        enzyme_reaction_2_para    meta_0    meta_1  \
Temperature                       0.000000e+00  0.000000  0.000000   
meta_0_para                       0.000000e+00 -0.293105  0.423547   
meta_3_para                       0.000000e+00  0.175863  0.074744   
enzyme_reaction_0_para            0.000000e+00 -0.586210  0.847093   
enzyme_reaction_1_para            0.000000e+00  0.644831 -0.274060   
enzyme_reaction_2_para            1.000000e+00 -0.351726 -0.149487   
meta_0                           -3.517262e-01  1.000000 -0.731718   
meta_1                           -1.494870e-01 -0.731718  1.000000   
meta_2                           -4.000000e-01 -0.410347  0.921837   
meta_3                            4.000000e-01  0.410347 -0.921837   
reaction_0                       -1.665335e-16  0.644831 -0.274060   
reaction_1                        0.000000e+00  0.644831 -0.274060   
reaction_2                        4.440892e-16  0.644831 -0.274060   

                              meta_2        meta_3    reaction_0  \
Temperature             0.000000e+00  0.000000e+00  0.000000e+00   
meta_0_para             4.000000e-01 -4.000000e-01  4.440892e-16   
meta_3_para             2.000000e-01 -2.000000e-01  8.326673e-17   
enzyme_reaction_0_para  8.000000e-01 -8.000000e-01  8.881784e-16   
enzyme_reaction_1_para -1.221245e-16  1.221245e-16  1.000000e+00   
enzyme_reaction_2_para -4.000000e-01  4.000000e-01 -1.665335e-16   
meta_0                 -4.103473e-01  4.103473e-01  6.448314e-01   
meta_1                  9.218366e-01 -9.218366e-01 -2.740595e-01   
meta_2                  1.000000e+00 -1.000000e+00  8.493206e-16   
meta_3                 -1.000000e+00  1.000000e+00 -8.493206e-16   
reaction_0              8.493206e-16 -8.493206e-16  1.000000e+00   
reaction_1             -3.441691e-16  3.441691e-16  1.000000e+00   
reaction_2              2.109424e-16 -2.109424e-16  1.000000e+00   

                          reaction_1    reaction_2  
Temperature             0.000000e+00  0.000000e+00  
meta_0_p

### <font color='white'> [2.1.1] Mutual information </font> 

In [63]:
momo.MI_group()

Temperature  meta_0_para  meta_3_para  \
Temperature                     inf     0.000000     0.000000   
meta_0_para                     0.0          inf     0.000000   
meta_3_para                     0.0     0.000000          inf   
enzyme_reaction_0_para          0.0     0.000000     0.000000   
enzyme_reaction_1_para          0.0     0.000000     0.000000   
enzyme_reaction_2_para          0.0     0.000000     0.000000   
meta_0                          0.0    -0.044913    -0.015708   
meta_1                          0.0    -0.098855    -0.002801   
meta_2                          0.0    -0.087177    -0.020411   
meta_3                          0.0    -0.087177    -0.020411   
reaction_0                      0.0     0.000000     0.000000   
reaction_1                      0.0     0.000000     0.000000   
reaction_2                      0.0     0.000000     0.000000   

                        enzyme_reaction_0_para  enzyme_reaction_1_para  \
Temperature                           0.000000                0.000000   
meta_0_para                           0.000000                0.000000   
meta_3_para                           0.000000                0.000000   
enzyme_reaction_0_para                     inf                0.000000   
enzyme_reaction_1_para                0.000000                     inf   
enzyme_reaction_2_para                0.000000                0.000000   
meta_0                               -0.210525               -0.268762   
meta_1                               -0.632156               -0.039039   
meta_2                               -0.510826                0.000000   
meta_3                               -0.510826                0.000000   
reaction_0                            0.000000                     inf   
reaction_1                            0.000000                     inf   
reaction_2                            0.000000                     inf   

                        enzyme_reaction_2_para    meta_0    meta_1     meta_2  \
Temperature                           0.000000  0.000000  0.000000   0.000000   
meta_0_para                           0.000000 -0.044913 -0.098855  -0.087177   
meta_3_para                           0.000000 -0.015708 -0.002801  -0.020411   
enzyme_reaction_0_para                0.000000 -0.210525 -0.632156  -0.510826   
enzyme_reaction_1_para                0.000000 -0.268762 -0.039039   0.000000   
enzyme_reaction_2_para                     inf -0.066030 -0.011300  -0.087177   
meta_0                               -0.066030       inf -0.383301  -0.092193   
meta_1                               -0.011300 -0.383301       inf  -0.947836   
meta_2                               -0.087177 -0.092193 -0.947836        inf   
meta_3                               -0.087177 -0.092193 -0.947836 -18.177780   
reaction_0                            0.000000 -0.268762 -0.039039   0.000000   
reaction_1                            0.000000 -0.268762 -0.039039   0.000000   
reaction_2                            0.000000 -0.268762 -0.039039   0.000000   

                           meta_3  reaction_0  reaction_1  reaction_2  
Temperature              0.000000    0.000000    0.000000    0.000000  
meta_0_para             -0.087177    0.000000    0.000000    0.000000  
meta_3_para             -0.020411    0.000000    0.000000    0.000000  
enzyme_reaction_0_para  -0.510826    0.000000    0.000000    0.000000  
enzyme_reaction_1_para   0.000000         inf         inf         inf  
enzyme_reaction_2_para  -0.087177    0.000000    0.000000    0.000000  
meta_0                  -0.092193   -0.268762   -0.268762   -0.268762  
meta_1                  -0.947836   -0.039039   -0.039039   -0.039039  
meta_2                 -18.177780    0.000000    0.000000    0.000000  
meta_3                        inf    0.000000    0.000000    0.000000  
reaction_0               0.000000         inf         inf         inf  
reaction_1               0.000000         inf         inf         inf  
react

### <font color='white'> [2.1.2] Plot </font> 

In [64]:
import numpy as np
np.sqrt(2*np.pi*np.e*1)

4.132731354122493

In [65]:
momo.parameters.df

Mean values Standard deviation
Temperature                 273.15                1.0
meta_0_para                    1.0                1.0
meta_3_para                    1.0                1.0
enzyme_reaction_0_para         1.0                1.0
enzyme_reaction_1_para         1.0                1.0
enzyme_reaction_2_para         1.0                1.0

In [66]:
#momo.plot(result="MI", label=True, value_in_cell=False )

## <font color='green'> [2.2] Sampling </font> 

### <font color='white'> [2.2.0] Let's create an exemple </font> 

In [67]:
from main import model

momo = model()
momo.read_SBML()

momo.enzymes.add_to_all_reaction()
momo.parameters.add_externals()
momo.parameters.add_enzymes()

momo.elasticity.s.half_satured()

Model created 
 
To add metabolite, use .metabolites.add_meta 
To add reaction,   use .reactions.add_reaction
Model created 
 
To add metabolite, use .metabolites.add_meta 
To add reaction,   use .reactions.add_reaction
0 error detected in your SBML file


In [68]:
import numpy as np
zz = np.zeros(momo.elasticity.p.df.shape)

print(zz.shape)
print(momo.elasticity.p.df.shape)
momo.elasticity.p.df = zz

momo.elasticity.p.df

(31, 44)
(31, 44)


Temperature  D_Glucose_para  Orthophosphate_para  \
PTS_RPTSsy              0.0             0.0                  0.0   
PGI_R02740              0.0             0.0                  0.0   
PFK_R04779              0.0             0.0                  0.0   
ALD_R01070              0.0             0.0                  0.0   
TIM_R01015              0.0             0.0                  0.0   
GAP_R01061              0.0             0.0                  0.0   
PGK_R01512              0.0             0.0                  0.0   
PGM_R01518              0.0             0.0                  0.0   
PGH_R00658              0.0             0.0                  0.0   
PYK_R00200              0.0             0.0                  0.0   
PDH_R00209              0.0             0.0                  0.0   
ZWF_R00835              0.0             0.0                  0.0   
GLH_R02035              0.0             0.0                  0.0   
PGD_R01528              0.0             0.0                  0.0   
RPI_R01056              0.0             0.0                  0.0   
RPE_R01529              0.0             0.0                  0.0   
TXT_R01641              0.0             0.0                  0.0   
TAL_R08575              0.0             0.0                  0.0   
TXT_R01067              0.0             0.0                  0.0   
CSN_R00351              0.0             0.0                  0.0   
ACN_R01325              0.0             0.0                  0.0   
ACN_R01900              0.0             0.0                  0.0   
ICD_R00709              0.0             0.0                  0.0   
KGD_R08549              0.0             0.0                  0.0   
SCS_R00405              0.0             0.0                  0.0   
SDH_R02164              0.0             0.0                  0.0   
FUM_R01082              0.0             0.0                  0.0   
MDH_R00342              0.0             0.0                  0.0   
PPC_R00345              0.0             0.0                  0.0   
Overflow                0.0             0.0                  0.0   
OxAConsumption          0.0             0.0                  0.0   

                NADPplus_para  NADPH_para  NADH_para  NADplus_para  ATP_para  \
PTS_RPTSsy                0.0         0.0        0.0           0.0       0.0   
PGI_R02740                0.0         0.0        0.0           0.0       0.0   
PFK_R04779                0.0         0.0        0.0           0.0       0.0   
ALD_R01070                0.0         0.0        0.0           0.0       0.0   
TIM_R01015                0.0         0.0        0.0           0.0       0.0   
GAP_R01061                0.0         0.0        0.0           0.0       0.0   
PGK_R01512                0.0         0.0        0.0           0.0       0.0   
PGM_R01518                0.0         0.0        0.0           0.0       0.0   
PGH_R00658                0.0         0.0        0.0           0.0       0.0   
PYK_R00200                0.0         0.0        0.0           0.0       0.0   
PDH_R00209                0.0         0.0        0.0           0.0       0.0   
ZWF_R00835                0.0         0.0        0.0           0.0       0.0   
GLH_R02035                0.0         0.0        0.0           0.0       0.0   
PGD_R01528                0.0         0.0        0.0           0.0       0.0   
RPI_R01056                0.0         0.0        0.0           0.0       0.0   
RPE_R01529                0.0         0.0        0.0           0.0       0.0   
TXT_R01641                0.0         0.0        0.0           0.0       0.0   
TAL_R08575                0.0         0.0        0.0           0.0       0.0   
TXT_R01067                0.0         0.0        0.0           0.0       0.0   
CSN_R00351                0.0         0.0        0.0           0.0       0.0   
ACN_R01325                0.0         0.0        0.0           0.0       0.0   
ACN_R01900                0.0         0.0        0.0           0.0       0.0   

In [69]:
print(f"Shape of the stoichio matrix : {momo.Stoichio_matrix.shape} \n")
print(f"numbers of metabolite in the model : {momo.metabolites.len} \n")
print(f"Numbers of reaction in the model : {momo.reactions.len} \n")
print(f"Numbers of enzyme in the model : {momo.enzymes.df.shape[0]} \n")
print(f"Numbers of parameters in the model : {momo.parameters.df.shape[0]} \n")

Shape of the stoichio matrix : (40, 31) 

numbers of metabolite in the model : 40 

Numbers of reaction in the model : 31 

Numbers of enzyme in the model : 31 

Numbers of parameters in the model : 44 



In [70]:
for index in momo.MI_group().index :
    print(index)

LinAlgError: Last 2 dimensions of the array must be square

### <font color='white'> [2.2.1] Updating the dataframe of the sampling data </font> 

In [ ]:
momo.data_sampling

Empty DataFrame
Columns: [Name, Type, Mean, Standard deviation, Distribution]
Index: []

In [ ]:
momo.add_sampling_data(["PTS_RPTSsy","enzyme_PTS_RPTSsy_para"], "elasticity_p", mean = True)

momo.data_sampling

Name          Type  Mean  \
0  [PTS_RPTSsy, enzyme_PTS_RPTSsy_para]  elasticity_p   0.0   

   Standard deviation Distribution  
0                   1      uniform

### <font color='white'> [2.2.2] Launching the sampling loop </font> 

In [ ]:
#import cProfile
#cProfile.run("momo.MI()")

In [ ]:
momo.sampling(10, result='rho', seed_constant=False)

running time of the code : 0.29105186462402344 
So 0.029105186462402344 per occurences !


array([[ 1.,  0.,  0., ..., nan, nan, nan],
       [ 0.,  1.,  0., ..., nan, nan, nan],
       [ 0.,  0.,  1., ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])

In [ ]:
momo.MI_group([["enzyme_PTS_RPTSsy_para","enzyme_PGI_R02740_para"],["FUM_R01082","MDH_R00342"],["PPC_R00345"]])

0   1   2
0  inf NaN NaN
1  NaN NaN NaN
2  NaN NaN NaN

In [ ]:
from main import *
momo = model()
momo.read_SBML()

momo.elasticity.s.half_satured()
momo.enzymes.add_to_all_reaction()
momo.parameters.add_enzymes()
momo.parameters.add_externals()

Model created 
 
To add metabolite, use .metabolites.add_meta 
To add reaction,   use .reactions.add_reaction
Model created 
 
To add metabolite, use .metabolites.add_meta 
To add reaction,   use .reactions.add_reaction
0 error detected in your SBML file


In [ ]:
a = momo.MI_group()

print(a.index[59])
a.loc[a.index[59]]

H2O


Temperature               inf
enzyme_PTS_RPTSsy_para    inf
enzyme_PGI_R02740_para    inf
enzyme_PFK_R04779_para    inf
enzyme_ALD_R01070_para    inf
                         ... 
FUM_R01082                inf
MDH_R00342                inf
PPC_R00345                inf
Overflow                  inf
OxAConsumption            inf
Name: H2O, Length: 115, dtype: float64

In [ ]:
momo.parameters.remove("Temperature")

Name of the removed parameter : Temperature


In [ ]:
#momo.plot(result='MI')

In [ ]:
momo.elasticity.p.df.shape[1]

43

# Test Part

In [ ]:
from main import model
momo = model()


momo.reactions.add("Reaction_0", {"X_in" : -1.0, "A" : 1.0})
momo.reactions.add("Reaction_1", {"A" : -1.0, "B" : 1.0})
momo.reactions.add("Reaction_2", {"B" : -1.0, "X_out" : 1.0})

momo.metabolites.add("X_in", True, 1)
momo.metabolites.add("A", False, 1)
momo.metabolites.add("B", False, 1)
momo.metabolites.add("X_out", True, 1)

momo.metabolites.change("X_in", external=True)
momo.metabolites.change("X_out", external=True)

momo.elasticity.s.half_satured()

momo.regulations.add("regu_0", "Reaction_0", "B", -0.5, allosteric=True)
momo.regulations.add("regu_1", "Reaction_0", "A", -0.5, allosteric=True)
momo.regulations.add("regu_2", "Reaction_1", "A", 0.5, allosteric=True)
momo.regulations.add("regu_3", "Reaction_1", "B", -0.5, allosteric=True)
momo.regulations.add("regu_4", "Reaction_2", "A", 0.5, allosteric=True)
momo.regulations.add("regu_5", "Reaction_2", "B", 0.5, allosteric=True)

momo.parameters.add_externals()
momo.enzymes.add_to_all_reaction()
momo.parameters.add_enzymes()

Model created 
 
To add metabolite, use .metabolites.add_meta 
To add reaction,   use .reactions.add_reaction
The metabolite "X_in" is already in the model !
The metabolite "A" is already in the model !
The metabolite "B" is already in the model !
The metabolite "X_out" is already in the model !


In [ ]:
momo.Stoichio_matrix

Reaction_0  Reaction_1  Reaction_2
X_in         -1.0         0.0         0.0
A             1.0        -1.0         0.0
B             0.0         1.0        -1.0
X_out         0.0         0.0         1.0

In [ ]:
momo.Jacobian

X_in             A    B
X_in  -0.5  1.000000e+00  0.5
A      0.5 -2.000000e+00  0.5
B     -0.5  3.330669e-16 -2.5

In [ ]:
momo.covariance

Temperature     X_in_para    X_out_para  \
Temperature                     1.0  0.000000e+00  0.000000e+00   
X_in_para                       0.0  1.000000e+00  0.000000e+00   
X_out_para                      0.0  0.000000e+00  1.000000e+00   
enzyme_Reaction_0_para          0.0  0.000000e+00  0.000000e+00   
enzyme_Reaction_1_para          0.0  0.000000e+00  0.000000e+00   
enzyme_Reaction_2_para          0.0  0.000000e+00  0.000000e+00   
X_in                            0.0 -6.250000e-01  3.750000e-01   
A                               0.0  1.250000e-01  1.250000e-01   
B                               0.0  1.250000e-01  1.250000e-01   
X_out                           0.0  3.750000e-01 -6.250000e-01   
Reaction_0                      0.0  5.551115e-17  4.857226e-17   
Reaction_1                      0.0  0.000000e+00  0.000000e+00   
Reaction_2                      0.0  0.000000e+00  0.000000e+00   

                        enzyme_Reaction_0_para  enzyme_Reaction_1_para  \
Temperature                       0.000000e+00            0.000000e+00   
X_in_para                         0.000000e+00            0.000000e+00   
X_out_para                        0.000000e+00            0.000000e+00   
enzyme_Reaction_0_para            1.000000e+00            0.000000e+00   
enzyme_Reaction_1_para            0.000000e+00            1.000000e+00   
enzyme_Reaction_2_para            0.000000e+00            0.000000e+00   
X_in                             -1.250000e+00           -5.000000e-01   
A                                 2.500000e-01           -5.000000e-01   
B                                 2.500000e-01            5.000000e-01   
X_out                             7.500000e-01            5.000000e-01   
Reaction_0                        1.110223e-16            1.665335e-16   
Reaction_1                        0.000000e+00            0.000000e+00   
Reaction_2                        0.000000e+00            0.000000e+00   

                        enzyme_Reaction_2_para          X_in             A  \
Temperature                       0.000000e+00  0.000000e+00  0.000000e+00   
X_in_para                         0.000000e+00 -6.250000e-01  1.250000e-01   
X_out_para                        0.000000e+00  3.750000e-01  1.250000e-01   
enzyme_Reaction_0_para            0.000000e+00 -1.250000e+00  2.500000e-01   
enzyme_Reaction_1_para            0.000000e+00 -5.000000e-01 -5.000000e-01   
enzyme_Reaction_2_para            1.000000e+00 -7.500000e-01 -2.500000e-01   
X_in                             -7.500000e-01  2.906250e+00  9.375000e-02   
A                                -2.500000e-01  9.375000e-02  4.062500e-01   
B                                -2.500000e-01 -4.062500e-01 -9.375000e-02   
X_out                             1.250000e+00 -2.593750e+00 -4.062500e-01   
Reaction_0                       -9.714451e-17 -1.656661e-16 -1.821460e-17   
Reaction_1                        0.000000e+00  0.000000e+00  0.000000e+00   
Reaction_2                        0.000000e+00  0.000000e+00  0.000000e+00   

                                   B         X_out    Reaction_0  Reaction_1  \
Temperature             0.000000e+00  0.000000e+00  0.000000e+00         0.0   
X_in_para               1.250000e-01  3.750000e-01  5.551115e-17         0.0   
X_out_para              1.250000e-01 -6.250000e-01  4.857226e-17         0.0   
enzyme_Reaction_0_para  2.500000e-01  7.500000e-01  1.110223e-16         0.0   
enzyme_Reaction_1_para  5.000000e-01  5.000000e-01  1.665335e-16         0.0   
enzyme_Reaction_2_para -2.500000e-01  1.250000e+00 -9.714451e-17         0.0   
X_in                   -4.062500e-01 -2.593750e+00 -1.656661e-16         0.0   
A                      -9.375000e-02 -4.062500e-01 -1.821460e-17         0.0   
B                       4.062500e-01  9.375000e-02  1.483189e-16         0.0   
X_out                   9.375000e-02  2.906250e+00  3.556183e-17         0.0   
Reaction_0              1.483189e-16  3.556183e-17  5.493715e-32         0.

In [ ]:
momo.pripri()

[[ 0.    -0.625  0.375 -1.25  -0.5   -0.75 ]
 [ 0.     0.125  0.125  0.25  -0.5   -0.25 ]
 [ 0.     0.125  0.125  0.25   0.5   -0.25 ]
 [ 0.     0.375 -0.625  0.75   0.5    1.25 ]]


In [ ]:
e = momo.elasticity.p.df.to_numpy()
print(e)

[[ 0.   0.5 -0.   1.   0.   0. ]
 [ 0.  -0.  -0.   0.   1.   0. ]
 [ 0.  -0.  -0.5  0.   0.   1. ]]


In [ ]:
C = np.array([  [-0.3125,  0.125,   0.1875],
                [ 0.4375, -0.375,  -0.0625],
                [ 0.0625,  0.375,  -0.4375],
                [-0.1875, -0.125,   0.3125]])

In [ ]:
np.dot(C,e)

array([[ 0.     , -0.15625, -0.09375, -0.3125 ,  0.125  ,  0.1875 ],
       [ 0.     ,  0.21875,  0.03125,  0.4375 , -0.375  , -0.0625 ],
       [ 0.     ,  0.03125,  0.21875,  0.0625 ,  0.375  , -0.4375 ],
       [ 0.     , -0.09375, -0.15625, -0.1875 , -0.125  ,  0.3125 ]])

In [ ]:
momo.Stoichio_matrix.to_numpy()

array([[-1.,  0.,  0.],
       [ 1., -1.,  0.],
       [ 0.,  1., -1.],
       [ 0.,  0.,  1.]])

In [ ]:
N_r = momo.Link_matrix[1].to_numpy()
print(N_r)

[[-1  0  0]
 [ 1 -1  0]
 [ 0  1 -1]]


In [ ]:
L = momo.Link_matrix[0]
print(L)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [-1. -1. -1.]]


In [ ]:
np.dot(L,N_r)

NameError: name 'L' is not defined